apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  TZ: "{{ .Values.global.TZ }}"
  DB_HOST: "{{ .Values.config.PACS_INTEGRATION_DB_HOST }}"
  DB_PORT: "{{ .Values.config.PACS_INTEGRATION_DB_PORT }}"
  DB_NAME: "{{ .Values.config.PACS_INTEGRATION_DB_NAME }}"
  OPENMRS_HOST: "{{ .Values.config.OPENMRS_HOST }}"
  OPENMRS_PORT: "{{ .Values.config.OPENMRS_PORT }}"
  CREATE_IMAGING_STUDY_ENABLED: "{{ .Values.config.CREATE_IMAGING_STUDY_ENABLED }}"
  CONCEPT_CODE_RESOLVER_SOURCE_PRIORITY: "{{ .Values.config.CONCEPT_CODE_RESOLVER_SOURCE_PRIORITY }}"
  HL7_SENDING_APPLICATION: "{{ .Values.config.HL7_SENDING_APPLICATION }}"
  HL7_SENDING_FACILITY: "{{ .Values.config.HL7_SENDING_FACILITY }}"
  HL7_RECEIVING_APPLICATION: "{{ .Values.config.HL7_RECEIVING_APPLICATION }}"
  HL7_RECEIVING_FACILITY: "{{ .Values.config.HL7_RECEIVING_FACILITY }}"

