# This is a basic workflow to help you get started with Actions

name: PACS-Integration-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - uses: actions/checkout@master
      - name: Build
        run: mvn clean install --file pom.xml        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@master
        with:
          name: pacs-integration target folder
          path: ./pacs-integration-webapp/target/
          retention-days: 5
